### ISSUE TITLE
holiday_jp.min.js のサブモジュール化

### ISSUE THREAD

**Issue by take0x** [Black092/oit_bus#7]
`holiday_jp.min.js` は [holiday_jp-js](https://github.com/holiday-jp/holiday_jp-js) のコードを使用しています。
サブモジュール化した方が元のリポジトリに追従できるため良いかと思います。

サブモジュール化する場合、プロトコルとしてはSSHを使用したいのですが特に問題なさそうでしょうか？
（SSHの鍵認証だとアクセストークンを発行しなくてもworkflowの操作が行えるため）

もしHTTPSを利用されているようであればこの案は一旦保留にしようと思います。

**Comment by take0x** [comment]
相対URLを使うことで対応できそうです。
https://qiita.com/aokomoriuta/items/598ba477f4d96a6f0395

この方法で検討してみます。

**Comment by Akirtn** [comment]
sshを使用して問題ありません，https,sshどちらも対応できるということで,相対URLでいいと思います．
サーバーが違う場合も考えると，ssh前提でしてしまった方が幸せな気もしますね．
